twist_mux:
  ros__parameters:
    use_stamped: true

    topics:
      joystick:
        topic: cmd_vel_joy
        timeout: 0.5
        priority: 100
      keyboard:
        topic: cmd_vel_keyboard
        timeout: 0.5
        priority: 90
